Django/230220/blog/urls.py
from django.urls import path, include
from . import views

# 전체 서비스에 지금 이 앱을 blog라고 부르기로 약속하는 것
app_name = "blog"
# 각 앱에 이름이 겹치는 파일 혹은, url이 겹치는 주소가 있을 수 있습니다.
# 그때 app_name : name 순으로 url을 호출해주시면
# 겹치는 파일명에도 불구하고 별개의 자리를 절대경로화해서 접근할 수 있습니다.

# blog 앱 내부 경로를 지정하는 부분
urlpatterns = [
    path('', views.BlogHome.as_view(paginate_by=5), name="home"),
    # paginate_by=개수: 속성들은 urls.py에서 호출할 때 아규먼트로 주거나 
    # views.py에서 디폴트 파라메터로 주면 됩니다.
    path('post_list/', views.PostList.as_view(), name="post_list"), # '' : blog 뒤에 달린 주소가 없음을 의미함 
    path('<int:pk>/', views.PostDetail.as_view()),
    path('about/', views.about_me, name="about_me"), # name="별명" // Alias
    path('contact/', views.contact, name="contact"),  
    # "blog" 라는 app의 "contact" 라는 별명으로 주소/blog/contact/를 호출할 수 있게 됩니다
    path('category/<str:slug>/', views.category_posts),
    path('tag/<str:slug>/', views.tag_posts, name="tag"),
    # path('index2/', views.index2)  # 주소/blog/index2
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>', views.PostUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),

    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('search/<str:q>/', views.PostSearch.as_view()),
    
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update')

]


Django/230220/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls')),
    path("admin/", admin.site.urls),
    path('blog/', include('blog.urls')), # blog 폴더 안의 urls(.py)를 참조해줘 라는 뜻
    path('markdownx/', include('markdownx.urls')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/230220/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Category 클래스 구현
# unique=True 전체 테이블에 해당 categoryName은 딱 1개만 만들어지도록 구현됩니다
# slugField : url로 통신하는 Django의 통신방식에 걸맞게 입력한 값이 URL화 되도록 자동으로 변경해줍니다
# 특수문자 에러처리, allow_unicode=True를 걸어두면 한국어 등 영어 외 언어도 사용 가능
class Category(models.Model):
    categoryName = models.CharField(max_length=30, unique=True) 
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True)

    def __str__(self):
        return self.categoryName

    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    # class Meta - 이 클래스를 사용하기 위한 간단한 지시나 설명을 넣어주는 class
    # 데이터의 '메타' 데이터와 같은 뜻입니다.
    class Meta:
        verbose_name_plural = 'categories'


class Tag(models.Model):
    tagName = models.CharField(max_length=30, unique=True) 
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True)

    def __str__(self):
        return self.tagName

    def get_absolute_url(self):
        return f'/blog/tag/{self.slug}/'


# Create your models here. 
# DB의 테이블을 좀더 쉽게 꺼내오기 위해 클래스 형식으로 바꿔주는 기능
class Post(models.Model):
    # 게시글에 필요한 필드: Primary Key, 제목, 내용, 작성일, 수정일, 작성자
    title = models.CharField(max_length=50)
    content = MarkdownxField()

    # upload_to= 경로
    # 어딘가 똑같은 폴더에 저장해주면 좋겠습니다
    # warm cold - 출신/년/월/일 경로로 처음에 지정을 해줄게요
    # blank=True : SQL 쿼리문으로 변환시 Null 가능(Nullable)한 필드를 만드는 옵션
    header_img = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)  # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    updated_at = models.DateTimeField(auto_now=True)  # 값을 변경할 수 있음. default 값으로 현재시간이 찍혀있음 
    
    # 작성자 - 외래키로 참조
    # CASCADE : User를 삭제하면 관련있는 모든 현재 테이블의 데이터 삭제
    # author = models.ForeignKey(User, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    # blank=True 글작성시 옵서녈 필드
    #  on_delete=models.SET_NULL, null=True 해당 필드와 걸려있는 다른 테이블의 키가 삭제될 때 None을 넣어줘
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True) 
    # 다대다 관계는 ManyToManyField를 통해 관계를 맺어줍니다
    tag = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[[{self.pk}] {self.title}            by {self.author}]'

    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

    def get_file_extension(self):
        return f'{self.file_upload}'.split('.')[-1]

    def get_content_markdown(self):
        return markdown(self.content)

   # 1. 모델에 함수를 추가해서 그 함수로 ORM을 뽑아낸다
   # 우리 의도: 전체 객체를 불러와서 그 중에 가장 최신글의 제목 뽑아내기
    def first_post_query(self):
        return Post.objects.all().last().title

# M - Comment  
class Comment(models.Model):
    # 게시글에 필요한 필드: Primary Key, 제목, 내용, 작성일, 수정일, 작성자
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    updated_at = models.DateTimeField(auto_now=True)  # 값을 변경할 수 있음. default 값으로 현재시간이 찍혀있음 
    # 글이 삭제되었을 때 댓글은 어떻게 남아있어야 할까 - CASCADE
    # CASCADE : User를 삭제하면 관련있는 모든 현재 테이블의 데이터 삭제
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    # 사용자가 탈퇴했을 때 댓글은 어떻게 남아있어야 할 것이냐 - CASCADE
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'[{self.author} / {self.content}]'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}' # #을 단 이유 : html에서 id를 의미하기 때문

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://picsum.photos/50/50/'

Django/230220/blog/forms.py
from .models import Comment
from django import forms
from django.contrib.auth.forms import UserChangeForm
# from django.contrib.auth.models import User # 이렇게 직접적으로 참고할수는 있으나 권장하지 않는 방법임
from django.contrib.auth import get_user_model


class CommentForm(forms.ModelForm): # 우리가 임의로 만들고 있는 모델 
    
    # 따로 상속받은 CreateView가 아니라 Form을 우리가 만들어서 사용하고 있기 때문에
    # 해당 Form에 대한 데이터를 메타클래스에 심어줍니다 
    class Meta:
        model = Comment
        fields = ('content', )


class CustomUserChangeForm(UserChangeForm) :
    
    class Meta :
        # model = User
        model = get_user_model()
        fields = ('email', 'password')

Django/230220/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404  # Function Based View 를 사용했습니다
from .models import Post, Category, Tag, Comment
from django.views.generic import ListView # 게시판형으로 데이터를 가지고 오는 클래스 
from django.views.generic.detail import DetailView
from django.views.generic import CreateView, UpdateView
from .forms import CommentForm
from django.core.exceptions import PermissionDenied # 인가 - 권한이 있는 경우가 아니면 발생시키는 예외처리
from django.utils.text import slugify # 빈칸이나 특수문자로 만들어진 문장을 한 단어씩 묶어주는 모듈 
# Login 기능 위해 Mixin 추가 
# Mixin은 객체 지향 프로그램에서 많이 쓰이는 개념으로 간단하게 말하여 다중상속을 가능하게 하는 클래스라고 할 수 있다. 여타의 언어들과는 다르게 파이썬은 다중 상속이 지원되지만 다중상속이 주는 모호함을 피하기 위해 많이 사용한다. 
# 따라서 Mixin은 상속이라기 보다는 포함, 확장이라는 개념으로 생각할 수 있다.
# 장고의 Mixin-메인 기능(비즈니스 로직)에 
# 인증, 로그 등 여러 부가 기능 사용 위해 다중상속 가능케하는 클래스
# 클래스에 Mixin 사용시 다른 클래스의 메서드 추가 가능
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm, CustomUserChangeForm

# 회원탈퇴
from django.views.decorators.http import require_POST
from django.contrib.auth import logout as auth_logout 
from django.contrib.auth.decorators import login_required

# 검색 - 장고 orm에서 쿼리문처럼 and나 or 조건을 쓰고 싶을때 사용할 수 있다.
from django.db.models import Q

# 화면 들어가서 확인 
# Mixin을 앞에 넣어줘야 인증 먼저 하고 해당 페이지로 넘어감
# LoginRequiredMixin은 사용자의 페이지에 로그인 되지 않은 다른 사용자가 접근하지 못하게 하고 로그인 페이지로 이동하게 하는 기능을 가지고 있는 클래스이다.
# 완성 후 실습: 글쓰기 버튼도 로그인한 사용자만 보이도록 변경해보세요 
class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'header_img', 'file_upload', 'category']
    # tag -> #카지노 #카지노_행님_20만원만 unique=True : 여러개 달았을 때 이미 있는 해시태그는 더 등록되지 않도록 
    # author -> 로그인 하는 순간부터 author 는 남아있기 때문에
    # created_at -> 작성되는 순간 자동 등록  
    # updated_at -> 수정되는 순간 자동 등록

    # CreateView가 내장 - 오버라이딩
    # 방문자가 form에 담에 보낸 유효한 정보를 담아 포스트를 만들고,
    # 이 포스트의 고유경로로 재전송(redirect)해주는 역할 
    # def form_valid(self, form):
    #     current_user = self.request.user
    #     if current_user.is_authenticated:
    #         form.instance.author = current_user
    #         return super(PostCreate, self).form_valid(form)
    #     else:
    #         return redirect('/blog/')

    # Tag 입력기능 추가
    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(tagName=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True) 
                        tag.save()
                    self.object.tag.add(tag)

            return response

        else:
                return redirect('/blog/')

# urls -> views -> templates(post_detail.html에 Edit 버튼 추가)
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    # fields = ['title', 'content', 'header_img', 'file_upload', 'category', 'tag']
    fields = ['title', 'content', 'header_img', 'file_upload', 'category']
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403

    # author 필드는 당연히 이전에 글을 생성한 작성자로 채워져있고, LoginRequiredMixin으로 로그인한 유저 확인하므로 form_valid는 오버라이딩하지 않음
    # 태그에 여러개 보내면 겹치지 않는 것만 새로 성성하는 기능은 필요하므로 get_context_data를 오버라이딩
    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tag.exists():
            tags_str_list = list()
            for t in self.object.tag.all():
                tags_str_list.append(t.tagName)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context

    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tag.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(tagName=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tag.add(tag)

        return response# Login 기능 위해 Mixin 추가 
# Mixin은 객체 지향 프로그램에서 많이 쓰이는 개념으로 간단하게 말하여 다중상속을 가능하게 하는 클래스라고 할 수 있다. 여타의 언어들과는 다르게 파이썬은 다중 상속이 지원되지만 다중상속이 주는 모호함을 피하기 위해 많이 사용한다. 
# 따라서 Mixin은 상속이라기 보다는 포함, 확장이라는 개념으로 생각할 수 있다.
# 장고의 Mixin-메인 기능(비즈니스 로직)에 
# 인증, 로그 등 여러 부가 기능 사용 위해 다중상속 가능케하는 클래스
# 클래스에 Mixin 사용시 다른 클래스의 메서드 추가 가능
from django.contrib.auth.mixins import LoginRequiredMixin

# 화면 들어가서 확인 
# Mixin을 앞에 넣어줘야 인증 먼저 하고 해당 페이지로 넘어감
# LoginRequiredMixin은 사용자의 페이지에 로그인 되지 않은 다른 사용자가 접근하지 못하게 하고 로그인 페이지로 이동하게 하는 기능을 가지고 있는 클래스이다.
# 완성 후 실습: 글쓰기 버튼도 로그인한 사용자만 보이도록 변경해보세요 
class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'header_img', 'file_upload', 'category', 'tag']
    # tag -> #카지노 #카지노_행님_20만원만 unique=True : 여러개 달았을 때 이미 있는 해시태그는 더 등록되지 않도록 
    # author -> 로그인 하는 순간부터 author 는 남아있기 때문에
    # created_at -> 작성되는 순간 자동 등록  
    # updated_at -> 수정되는 순간 자동 등록

    # CreateView가 내장 - 오버라이딩
    # 방문자가 form에 담에 보낸 유효한 정보를 담아 포스트를 만들고,
    # 이 포스트의 고유경로로 재전송(redirect)해주는 역할 
    # def form_valid(self, form):
    #     current_user = self.request.user
    #     if current_user.is_authenticated:
    #         form.instance.author = current_user
    #         return super(PostCreate, self).form_valid(form)
    #     else:
    #         return redirect('/blog/')

    # Tag 입력기능 추가
    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
            form.instance.author = current_user
            response = super(PostCreate, self).form_valid(form)

            # tag를 쉼표 단위로 넣으면 끊도록 만들어놓은 로직
            tags_str = self.request.POST.get('tags_str')
            if tags_str:
                tags_str = tags_str.strip()

                tags_str = tags_str.replace(',', ';')
                tags_list = tags_str.split(';')

                for t in tags_list:
                    t = t.strip()
                    tag, is_tag_created = Tag.objects.get_or_create(tagName=t)
                    if is_tag_created:
                        tag.slug = slugify(t, allow_unicode=True)
                        tag.save()
                    self.object.tag.add(tag)

            return response

        else:
                return redirect('/blog/')

# urls -> views -> templates(post_detail.html에 Edit 버튼 추가)
class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    # fields = ['title', 'content', 'header_img', 'file_upload', 'category', 'tag']
    fields = ['title', 'content', 'header_img', 'file_upload', 'category', 'tag']
    
    # 로그인한 상태에서 작성자(request.user) 가 object.author(Post.objects.get(pk=pk))과 일치하는지 확인 필요
    def dispatch(self, request, *args, **kwargs): # 방문자가 GET으로 요청했는데 POST로 요청했는지 확인하는 기능
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied # 권한 없는 사람이 글 수정하려 하면 403

    # author 필드는 당연히 이전에 글을 생성한 작성자로 채워져있고, LoginRequiredMixin으로 로그인한 유저 확인하므로 form_valid는 오버라이딩하지 않음
    # 태그에 여러개 보내면 겹치지 않는 것만 새로 성성하는 기능은 필요하므로 get_context_data를 오버라이딩
    def get_context_data(self, **kwargs):
        context = super(PostUpdate, self).get_context_data()
        if self.object.tag.exists():
            tags_str_list = list()
            for t in self.object.tag.all():
                tags_str_list.append(t.tagName)
            context['tags_str_default'] = '; '.join(tags_str_list)

        return context

    # 포스트에 태그를 추가하려면 이미 데이터베이스에 저장된 pk를 부여받아서 수정해야 함, 그래서 form_valid()를 통해 결과를 response 변수에 임시 담아두고
    # 서로 저장된 포스트를 self.object로 저장함.
    def form_valid(self, form):
        response = super(PostUpdate, self).form_valid(form)
        self.object.tag.clear()

        tags_str = self.request.POST.get('tags_str')
        if tags_str:
            tags_str = tags_str.strip()
            tags_str = tags_str.replace(',', ';')
            tags_list = tags_str.split(';')

            for t in tags_list:
                t = t.strip()
                tag, is_tag_created = Tag.objects.get_or_create(tagName=t)
                if is_tag_created:
                    tag.slug = slugify(t, allow_unicode=True)
                    tag.save()
                self.object.tag.add(tag)

        return response



Django/230220/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>POSTLIST</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            {% include 'blog/navbar.html' %}
            {% block page_area %}

            {# 메인에 들어갈 부분을 채워 넣습니다 #}
            
            {% endblock %}
        

        </main>
            {% include 'blog/footer.html' %}


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

Django/230220/blog/templates/blog/navbar.html
{% load socialaccount %}
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'blog:home' %}">YEONJI KIM</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:home' %}">Home</a></li>
                            <!-- <li class="nav-item"><a class="nav-link" href="about/">About</a></li> -->
                              <!-- # 등록된 이름만으로 위치를 찾기 때문에 도메인 주소나 path에 영향을 받지 않는다. 다만, 자기 프로젝트 내부에서만 사용 가능하다. -->
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:about_me' %}">About</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'blog:contact' %}">Contact</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'blog:home' %}">Blog Home</a></li>
                                    <li><a class="dropdown-item" href="{% url 'blog:post_list' %}">Blog Post</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="portfolio-overview.html">Portfolio Overview</a></li>
                                    <li><a class="dropdown-item" href="portfolio-item.html">Portfolio Item</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            {% if user.is_authenticated %}
                                    <div class="d-flex justify-content-between align-items-center">
                                        <span class="text-secondary fw-bold"> <a href="{% url 'blog:update' %}">{{ user.username }}</a> &nbsp</span>
                                        <a class="btn btn-secondary" href="/accounts/logout/" role="button">로그아웃</a> &nbsp
                                        <form action="{% url 'blog:delete' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="submit" class="btn btn-secondary" value="회원탈퇴">
                                        </form>
                                    </div>
                            {% else %}
                                <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#loginModal">
                                로그인
                              </button>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>


            <!-- Modal -->
            <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title fs-5" id="loginModalLabel">로그인</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                                    {# 구글 OAuth #}
                                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>&nbsp&nbsp Log in with Google</a><br />
                                    <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/"><i class="far fa-envelope"></i>&nbsp&nbsp Log in with E-mail</a><br />
                                    <a role="button" class="btn-dark btn-block btn-sm" href="/accounts/signup/"><i class="far fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</a>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                        </div>
                    </div>
                </div>
            </div>
            

Django/230220/blog/templates/blog/search_widget.html
<div style="top: 200px;" class="col sticky-top">
    <!-- Search Widget -->
    <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="검색어를 입력하세요" id="search-input">
                <span class="input-group-btn">
                        <button class="btn btn-dark" type="button" onclick="searchPost();">검색</button>
                    </span>
            </div>
        </div>
    </div>

    <!-- Categories Widget -->
    <div class="card my-3" id="categories-card">
        <h5 class="card-header">Categories</h5>
        <div class="card-body m-3">
            <div class="row">

                <ul>
                    {% for category in categories %}
                        <li>
                            <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                        </li>
                    {% endfor %}
                    <li>
                        <a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</div>

<script>
function searchPost(){
let searchValue = document.getElementById('search-input').value.trim();
if (searchValue.length > 1){
    location.href="/blog/search/" + searchValue + "/";
}
else{
    alert('검색어('+ searchValue +')가 너무 짧습니다.');
}
};

document.getElementById('search-input').addEventListener('keyup', function(event){
if(event.key === 'Enter'){
    searchPost();
}
});
</script>